# Generated by Django 3.0.6 on 2020-05-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200511_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='type',
            new_name='category',
        ),
    ]
